WorldWeather: {
    title: World weather demo,
    subTitle: "A demo web application that retreving data by AngularJs service",
    date: 2015.2,
    img_link: /images/worldWeather.png,
    link: https://github.com/wghglory/guanghui.Weather,
    tag: ["MVC","WebApi","AngularJs1","Bootstrap"],
    abstract: "This project uses ado.net to retrieve data from local sqlserve db. AngularJs controller, service, filter, directive are used to talk with server."
}
Mean: {
    title: MEAN web basic architect,
    subTitle: "Nodejs, angularjs1, socketIO, test framework, grunt automation",
    date: 2016.12,
    img_link: /images/mean.png,
    link: https://github.com/wghglory/nodejs.mea1n4.testAndAutomation,
    tag: ["Mongodb","AngularJs","Nodejs","Express","Mongoose"],
    abstract: "This demo porjects uses Nodejs, angularJs1, socketIO, test framework, grunt automation and horizontal architecture."
}
MeanBlog: {
    title: MEAN blog demo,
    subTitle: "Nodejs, jQuery, ES2015",
    date: 2017.1,
    img_link: /images/nodejs.blog.ejs.png,
    link: https://github.com/wghglory/nodejs.blog.ejs,
    tag: ["Mongodb","AngularJs1","Nodejs","Express","Mongoose"],
    abstract: "This project includes admin CRUD, regular user authentication, article review, etc."
}
